### ISSUE TITLE
How to generate ref struct? 

### ISSUE THREAD

**Issue by lilhammer111** [cloudwego/cloudwego.github.io#892]
I generate my structures in remote repository in advance, and then created my idl-ref.yml file in the same directory as the idl file in my local project.Everything is ready. I executed the  command like `kitex --module xxx xxx.thrift` in the directory of idl-ref.yml,but got the original code generated by kitex instead of a reference. What went wrong? 
Here is my `idl-ref.yml` file:
```yaml
ref:
  common_rpc.thrift: "xxxx.com/public-repo/ref/kitex_gen/common_rpc"
  user.thrift: "xxx.comt/public-repo/ref/kitex_gen/micro_user"
```
